# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=10)),
                ('last_name', models.CharField(default='', max_length=10)),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FormCreateAccount',
        ),
    ]
