# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chfapp', '0002_auto_20160205_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('joincode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='CreateAccount',
            new_name='AdminForm',
        ),
    ]
