# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chfapp', '0004_newuserform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUserForm',
            new_name='Users',
        ),
    ]
