# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chfapp', '0006_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('joincode', models.CharField(max_length=50)),
                ('enforceUser', models.NullBooleanField()),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Admin')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Users')),
            ],
        ),
    ]
