# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chfapp', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('superUser', models.IntegerField()),
                ('userLimit', models.IntegerField()),
                ('inactiveUsers', models.NullBooleanField()),
                ('revisionState', models.NullBooleanField()),
                ('allowReplayActivity', models.NullBooleanField()),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Admin')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Event')),
            ],
        ),
    ]
