# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chfapp', '0008_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('inactive', models.NullBooleanField()),
                ('activityCompleted', models.NullBooleanField()),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Activity')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Users')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activitysession',
            unique_together=set([('userID', 'activityID', 'startTime')]),
        ),
    ]
